
List<Integer> listInteger = new List<Integer> ();

listInteger.add(5);
listInteger.add(15);
listInteger.add(7);
listInteger.add(51);
listInteger.add(25);

Carsamba.sum(listInteger);
//index 4
//5 elemanli
// system.debug(listInteger);
// system.debug('size --> ' +listInteger.size());
// system.debug('Index 0 olan eleman --> ' +listInteger.get(0));
// system.debug('Index 0 olan eleman --> ' + listInteger[0]);


